common/models/Productos.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "productos".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property integer $activo
 * @property integer $imagen
 * @property string $keywords
 * @property integer $orden
 * @property integer $fecha_creacion
 * @property integer $fecha_modificacion

 *
 * @property Archivos $imagen0
 * @property ProductosMultimedia[] $productosMultimedia
 * @property Archivos[] $archivos
 * @property ProductosXCategorias[] $productosXCategorias
 * @property ProductosCategorias[] $categorias
 */
class Productos extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'productos';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
                [['nombre', 'activo','orden'], 'required'],
                [['descripcion'], 'string'],
                [['activo', 'imagen', 'orden', 'fecha_creacion', 'fecha_modificacion'], 'integer'],
                [['nombre'], 'string', 'max' => 96],
                [['keywords'], 'string', 'max' => 255],
                [['imagen'], 'exist', 'skipOnError' => true, 'targetClass' => Archivos::className(), 'targetAttribute' => ['imagen' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'descripcion' => 'Descripcion',
            'activo' => 'Activo',
            'imagen' => 'Imagen',
            'keywords' => 'Keywords',
            'palabras_clave' => 'Palabras Clave',
            'orden' => 'Orden',
            'fecha_creacion' => 'Fecha Creacion',
            'fecha_modificacion' => 'Fecha Modificacion',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImagen0() {
        return $this->hasOne(Archivos::className(), ['id' => 'imagen']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductosXCategorias() {
        return $this->hasMany(ProductosXCategorias::className(), ['producto_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategorias() {
        return $this->hasMany(ProductosCategorias::className(), ['id' => 'categoria_id'])->viaTable('productos_x_categorias', ['producto_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery 
     */
    public function getProductosMultimedia() {
        return $this->hasMany(ProductosMultimedia::className(), ['producto_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery 
     */
    public function getArchivosMultimedia() {
        return $this->hasMany(Archivos::className(), ['id' => 'archivos_id'])->viaTable('productos_multimedia', ['producto_id' => 'id']);
    }

}

backend/controllers/ProductosController.php
<?php

namespace backend\controllers;

use Yii;
use yii\helpers\Html;
use common\models\Productos;
use common\models\Archivos;
use common\models\search\ProductosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Json;

/**
 * ProductosController implements the CRUD actions for Productos model.
 */
class ProductosController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'delete-multiple' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                        [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'delete-multiple', 'multimedia-remove'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Productos models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new ProductosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Productos model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {

        $model = $this->findModel($id);

        return $this->renderPartial('view', [
                    'model' => $model,
        ]);
    }

    /**
     * Creates a new Productos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Productos();

        if ($model->load(Yii::$app->request->post())) {

            $model->fecha_creacion = time();
            $model->fecha_modificacion = time();




            $multimedia_uploaded = Yii::$app->request->post('multimedia-ids');
            if (!is_null(Yii::$app->request->post('palabras_clave')))
                $model->keywords = implode(',', Yii::$app->request->post('palabras_clave'));




            if ($model->save()) {
                \Yii::$app->getSession()->setFlash('success', 'Los datos han sido guardados exitosamente.');


                $relation_error = false;
                if (!empty($multimedia_uploaded)) {
                    $relation_error = $this->relacionarMultimedia($multimedia_uploaded, $model);
                }

                if ($relation_error) {
                    \Yii::$app->getSession()->setFlash('warning', 'Hubo un problema al relacionar los archivos multimedia cargados. Sin embargo los datos de la nota han sido guardados correctamente.');
                }


                return $this->redirect(['index']);
            } else
                \Yii::$app->getSession()->setFlash('danger', Html::errorSummary($model));
        }


        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    //Archivos list string con ids separados con coma "1,2,3,4"
    protected function relacionarMultimedia($archivoslist, $model) {
        $relation_error = false;
        foreach (explode(',', $archivoslist) as $f_id) {


            $f_h = \common\utils\Archivo::loaddb($f_id);
            $archivo = $f_h->getDbRecord();
            try{
                $model->link('archivosMultimedia', $archivo);
            } catch (Exception $ex) {
                $relation_error = true;
            }
        }


        return $relation_error;
    }

    public function actionMultimediaRemove($id) {

        //implementar
        $model = $this->findModel($id);

        $file_id = Yii::$app->request->post("multimedia_id");

        $archivo = Archivos::findOne($file_id);

        if (is_null($archivo))
            return true;


        $model->unlink('archivosMultimedia', $archivo, true);
    }

    public function actionDeleteMultiple() {
        $pk = Yii::$app->request->post('pk'); // Array or selected records primary keys
        // Preventing extra unnecessary query
        if (!$pk) {
            return;
        }
        return Productos::deleteAll(['id' => $pk]);
    }

    /**
     * Updates an existing Productos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);


        if ($model->load(Yii::$app->request->post())) {


            $multimedia_uploaded = Yii::$app->request->post('multimedia-ids');
            $model->fecha_modificacion = time();

            if (!is_null(Yii::$app->request->post('palabras_clave')))
                $model->keywords = implode(',', Yii::$app->request->post('palabras_clave'));



            $relation_error = false;
            if (!empty($multimedia_uploaded)) {
                $relation_error = $this->relacionarMultimedia($multimedia_uploaded, $model);
            }

            if ($relation_error) {
                \Yii::$app->getSession()->setFlash('warning', 'Hubo un problema al relacionar los archivos multimedia cargados. Sin embargo los datos de la nota han sido guardados correctamente.');
            }


            if ($model->save()) {
                \Yii::$app->getSession()->setFlash('success', 'Los datos han sido modificados exitosamente.');
                return $this->redirect(['index']);
            } else
                \Yii::$app->getSession()->setFlash('danger', Html::errorSummary($model));
        }


        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Productos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {


        $this->findModel($id)->delete();

        if (Yii::$app->request->isAjax) {
            return Json::encode([
                        'success' => true,
            ]);
        } else
            return $this->redirect(['index']);
    }

    /**
     * Finds the Productos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Productos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Productos::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('La página solicitada no existe.');
        }
    }

}

frontend/controllers/ProductosController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Productos;
use common\models\search\ProductosSearch;
use yii\web\NotFoundHttpException;

class ProductosController extends \yii\web\Controller {

    public function actionDetalle($id) {
        
        
        $model = $this->findModel($id);
        
        $searchModel = new ProductosSearch();
        $relacionados = $searchModel->searchRelacionadas($model, $id);
        
        
        
        return $this->render('detalle',[ 'model' => $model ,'relacionados' => $relacionados]);
    }

    public function actionIndex() {

        
        $search = Yii::$app->request->get('q');
        $searchModel = new ProductosSearch();
        $dataProvider = $searchModel->searchFront($search);
        


        return $this->render('index',['productos_dataprovider' => $dataProvider , 'search' => $search]);
    }

    /**
     * Finds the Productos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Productos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Productos::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('La página solicitada no existe.');
        }
    }

}

frontend/views/productos/_list_productos.php
<?php

use yii\widgets\ListView;
use nirvana\infinitescroll\InfiniteScrollPager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * https://github.com/kop/yii2-scroll-pager
 * ListView::widget([
  'dataProvider' => $dataProvider,
  'itemOptions' => ['class' => 'item'],
  'itemView' => '_item_view',
  'pager' => ['class' => \kop\y2sp\ScrollPager::className()]
  ]); */
?>

<?=

ListView::widget([
    'dataProvider' => $dataProvider,
    'id' => 'list-productos',
    //'layout' => '<div class="items">{items}</div>{pager}',
    'layout' => '<div class="items">{items}</div><div class="list-productos-actions">{pager}</div>',
    'itemOptions' => ['tag' => 'div', 'class' => 'col-lg-4 col-md-4 col-sm-6 col-xs-12 list-item list-productos-item'],
    'options' => [
	'tag' => 'div',
	'class' => 'list-items list-productos',
    ],
    'itemView' => '_list_productos_item',
    'pager' => [
	'class' => InfiniteScrollPager::className(),
	'widgetId' => 'list-productos',
	'itemsCssClass' => 'items',
	'nextPageLabel' => 'Cargar más Notas',
        'contentLoadedCallback' => 'function (data) { if(data.length < ' . $dataProvider->pagination->pageSize . ') $(".list-productos-actions").hide(); }',
	'linkOptions' => [
	    'class' => 'btn btn-primary',
	],
	'pluginOptions' => [
	    'loading' => [
		'msgText' => "<em>Cargando...</em>",
		'finishedMsg' => "<em>No se han encontrado mas resultados</em>",
	    ],
	    'behavior' => InfiniteScrollPager::BEHAVIOR_TWITTER,
	],
    ],
]);
?>

frontend/views/productos/_list_productos_item.php
<?php

use yii\helpers\Url;
use common\utils\Utils;

if (is_null($model))
    return '';

if (!isset($showlink))
    $showlink = true;
?>




<div class="list-productos-producto">

    <a href="<?= Url::toRoute(['/productos/detalle', 'id' => $model->id, 'slug' => Utils::slugify($model->nombre)]) ?>">
        <img src="<?= $model->imagen0->getUrl("16/9x1") ?>"  alt="..." class="img-background">
    </a>
    <div class="list-productos-producto-categorias">
        <?php foreach ($model->categorias as $categoria): ?>
            <a href="#" class="categoria-item"><?= $categoria->nombre ?></a>
        <?php endforeach; ?>
    </div>

    <h3><a href="<?= Url::toRoute(['/productos/detalle', 'id' => $model->id, 'slug' => Utils::slugify($model->nombre)]) ?>" > <?= $model->nombre ?> </a></h3>

    <p class="list-productos-productos-desc"><?= Utils::limit_text($model->descripcion, 20) ?> </p>
    
    
    
    <?php if ($showlink): ?>
        <a href="<?= Url::toRoute(['/productos/detalle', 'id' => $model->id, 'slug' => Utils::slugify($model->nombre)]) ?>" class="btn btn-primary">VER DETALLE</a>

    <?php endif; ?>

</div><!-- /.list-item-inner -->

frontend/views/productos/detalle.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = $model->nombre;

Yii::$app->view->params['title-seo'] = $model->nombre;
//Yii::$app->view->params['description-seo'] = "";
?>

<div class="col-lg-10">
    <div class="article-head">

        <h3><?= $model->nombre ?></h3>
        <img src="<?= $model->imagen0->getUrl("16/9x1") ?>"  alt="..." class="img-responsive">
        <p><?= $model->descripcion ?></p>
        <?= $this->render('/common/socials'); ?>
    </div><!-- /.article__head-inner -->


</div>



<div class="col-lg-2">

    <h4 class="others">Otros productos que te pueden interesar</h4>
    <?php if (count($relacionados->models) > 0): ?>
        <?= $this->render('_list_productos', ['dataProvider' => $relacionados]); ?>

    <?php endif; ?>

</div>

frontend/views/productos/index.php
<?php
/* @var $this yii\web\View */
$this->title = 'Productos';
Yii::$app->view->params['title-seo'] = 'Productos';
//Yii::$app->view->params['description-seo'] 
?>



<section class="productos">
    <h1>Productos</h1>
    <form action="?" method="get">
        <label for="q" >Search</label>

        <input type="search" name="q" id="q" value="<?= $search ?>" placeholder="Buscar" class="search__field">

        <button type="submit" class="search__btn">
           Buscar
        </button>
    </form> 

    <?= $this->render('_list_productos', [ 'dataProvider' => $productos_dataprovider ]); ?>
</section>