backend/controllers/ImagenesController.php
<?php

namespace backend\controllers;

use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\Archivos;
use Yii;
use yii\helpers\Json;

class ImagenesController extends \yii\web\Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            /* 'verbs' => [
              'class' => VerbFilter::className(),
              'actions' => [
              'delete' => ['POST'],
              'delete-multiple' => ['POST'],
              ],
              ], */

            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                        [
                        'actions' => ['index', 'recortar', 'subir', 'borrar', 'input'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionInput() {
        $model = new Archivos();
        $dataProvider = $model->searchImagenes();

        return $this->renderAjax('input', [
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionIndex() {
        //return $this->render('index');


        $model = new Archivos();
        $dataProvider = $model->searchImagenes();

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionBorrar($id) {
        $imagen = \common\utils\Imagen::loaddb($id);

        if (!is_null($imagen))
            $imagen->delete();
    }

    public function actionRecortar($id) {

        $imagen = \common\utils\Imagen::loaddb($id);
        $recortes = \common\utils\Imagen::getRecortes();
        if (Yii::$app->request->isAjax) {



            if (Yii::$app->request->isPost) {

                $recorte_selected = Yii::$app->request->post('recorte');
                $cropdata = Yii::$app->request->post('cropdata');

                $imagen->cropmanual($cropdata['width'], $cropdata['height'], $cropdata['x'], $cropdata['y'], $imagen->getFiletoRecorte($recorte_selected));
                return Json::encode([
                            'success' => true,
                ]);
            }

            return $this->renderAjax('recortar', ['id' => $id, 'model' => $imagen, 'recortes' => $recortes]);
        }

        return $this->render('recortar', ['id' => $id, 'model' => $imagen, 'recortes' => $recortes]);
    }

    public function actionSubir() {

        if (Yii::$app->request->isAjax) {
            if (Yii::$app->request->isPost) {

                $f_helper = \common\utils\Imagen::uploadArchivo('imagen-upload', "/galeria/", true);




                if (!$f_helper->hasError) {

                    $tamaño = getimagesize($f_helper->getFile());

                    if ($tamaño[0] < 1280 || $tamaño[1] < 720) {
                        return Json::encode([
                                    'error' => 'La imagen debe tener un tamaño mínimo de 1280x720',
                        ]);
                        $f_helper->delete();
                    }
                    $f_helper->generarRecortes();

                    return Json::encode([
                                'success' => true,
                                'uploadedid' => $f_helper->db_id,
                                'uploadedurl' => $f_helper->getUrl()
                    ]);
                } else {

                    return Json::encode($f_helper->errorReport);
                }
            }
            return $this->renderAjax('subir');
        }

        return $this->render('subir');
    }

}

backend/views/imagenes/_inputitem.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * data-toggle="slidePanel" data-url="<?= Url::toRoute(['/imagenes/recortar', 'id' => $model->id]) ?>"
 */
?>



<a href="javascript:void(0)" class="img-input-select" data-imgid="<?= $model->id ?>" data-imgurl="<?= $model->getUrl() ?>">
    <img src="<?= $model->getUrl() ?>" class="image img-thumbnail img-rounded img-fluid" alt="..." >
</a>

<?php
$this->registerJs(
<<<JAVASCRIPT

  /* $('.btn-imagen-delete').bind("ajax-call-response",function(e){
        toastr["success"]("La imagen ha sido eliminada exitosamente!");
        $.pjax.reload({container: '#pjax-imagenes-container', timeout: 10000});
   })*/
        
JAVASCRIPT
);

backend/views/imagenes/_thumbitem.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * data-toggle="slidePanel" data-url="<?= Url::toRoute(['/imagenes/recortar', 'id' => $model->id]) ?>"
 */
?>



<div class="media-item" >
    <!--<div class="checkbox-custom checkbox-primary checkbox-lg">
        <input type="checkbox" class="selectable-item" id="media_12" />
        <label for="media_12"></label>
    </div>-->
    <div class="image-wrap">
        <img src="<?= $model->getUrl() ?>" class="image img-rounded" alt="...">
    </div>
    <div class="info-wrap">
        <div class="dropdown">
            <span class="icon md-settings" data-toggle="dropdown" aria-expanded="false" role="button"
                  data-animation="scale-up"></span>
            <div class="dropdown-menu dropdown-menu-right" role="menu">
                <?= Html::a('<i class="icon md-edit" aria-hidden="true"></i>Recortar', ['/imagenes/recortar', 'id' => $model->id], ['class' => 'dropdown-item remote-modal', 'target' => '_BLANK', 'data-target' => '#modal-recortes', 'data-toggle' => 'modal']);
                ?>
                <?= "" /* Html::a('<i class="icon md-download" aria-hidden="true"></i>Descargar', ['/imagenes/recortar', 'id' => $model->id], ['class' => 'dropdown-item remote-modal', 'target' => '_BLANK', 'data-target' => '#modal-recortes', 'data-toggle' => 'modal']);
                 */ ?>
                <?= Html::a('<i class="icon md-delete" aria-hidden="true"></i>Borrar', 'javascript:void(0)', ['class' => 'dropdown-item btn-imagen-delete ajax-call', 'target' => '_BLANK', 'data-method' => 'POST', 'data-params' => '', 'data-url' => Url::toRoute(['/imagenes/borrar', 'id' => $model->id])]);
                ?>

            </div>
        </div>
        <div class="title"><?= $model->alt ?></div>
        <div class="time"><?= \common\utils\Utils::time_elapsed_string(date('d-m-Y h:m:s', $model->fecha_subida)) ?></div>
        <div class="media-item-actions btn-group">





            <?= Html::a('<i class="icon md-edit" aria-hidden="true"></i>', ['/imagenes/recortar', 'id' => $model->id], ['class' => 'btn btn-icon btn-pure btn-default remote-modal', 'target' => '_BLANK', 'data-target' => '#modal-recortes', 'data-toggle' => 'modal']);
            ?>
            <?= "" /* Html::a('<i class="icon md-download" aria-hidden="true"></i>', ['/imagenes/recortar', 'id' => $model->id], ['class' => 'btn btn-icon btn-pure btn-default remote-modal', 'target' => '_BLANK', 'data-target' => '#modal-recortes', 'data-toggle' => 'modal']);
             */ ?>
            <?= Html::a('<i class="icon md-delete" aria-hidden="true"></i>', 'javascript:void(0)', ['class' => 'btn btn-icon btn-pure btn-imagen-delete btn-default ajax-call', 'data-method' => 'POST', 'data-params' => '', 'data-url' => Url::toRoute(['/imagenes/borrar', 'id' => $model->id])]);
            ?>

        </div>
    </div>
</div>



<?php
$this->registerJs(
<<<JAVASCRIPT

   $('.btn-imagen-delete').bind("ajax-call-response",function(e){
        toastr["success"]("La imagen ha sido eliminada exitosamente!");
        $.pjax.reload({container: '#pjax-imagenes-container', timeout: 10000});
   })
        
JAVASCRIPT
);

backend/views/imagenes/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\ListView;
use nirvana\infinitescroll\InfiniteScrollPager;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\NoticiasSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

\backend\assets\ImagenesAsset::register($this);

$this->title = 'Imágenes';

$this->params['breadcrumbs'][] = $this->title;
Yii::$app->params['page-header-show'] = false;
Yii::$app->params['page-content-show'] = false;
Yii::$app->params['page-body-class'] = 'app-media page-aside-left site-menubar-unfold';

$this->registerCss("
    
    #infscr-loading{
        text-align:center;
    }
    
    #list-imagenes ul.pagination {
    margin:0;
    }
    #list-imagenes ul.pagination li.next{
                width: 100%;
                text-align: center;
    }


    }
    
    ");
?>



<!--
<div class="page-aside">
    <div class="page-aside-switch">
        <i class="icon md-chevron-left" aria-hidden="true"></i>
        <i class="icon md-chevron-right" aria-hidden="true"></i>
    </div>
    <div class="page-aside-inner page-aside-scroll">
        <div data-role="container">
            <div data-role="content">
                <section class="page-aside-section">
                    <h5 class="page-aside-title">Main</h5>
                    <div class="list-group">
                        <a class="list-group-item active" href="javascript:void(0)"><i class="icon md-view-dashboard" aria-hidden="true"></i>Galería</a>
                        <a class="list-group-item" href="javascript:void(0)"><i class="icon md-image-o" aria-hidden="true"></i>Documentación</a>
                    </div>
                </section>
<!-- 
 <section class="page-aside-section">
     <h5 class="page-aside-title">Filter</h5>
     <div class="list-group">
         <a class="list-group-item" href="javascript:void(0)"><i class="icon md-image" aria-hidden="true"></i>Images</a>
         <a class="list-group-item" href="javascript:void(0)"><i class="icon md-volume-up" aria-hidden="true"></i>Audio</a>
         <a class="list-group-item" href="javascript:void(0)"><i class="icon md-videocam" aria-hidden="true"></i>Video</a>
         <a class="list-group-item" href="javascript:void(0)"><i class="icon md-file" aria-hidden="true"></i>Notes</a>
         <a class="list-group-item" href="javascript:void(0)"><i class="icon md-link" aria-hidden="true"></i>Links</a>
         <a class="list-group-item" href="javascript:void(0)"><i class="icon md-receipt" aria-hidden="true"></i>Files</a>
     </div>
 </section>

</div>
</div>
</div>
</div> -->

<!-- Media Content -->
<div class="page-main">
    <!-- Media Content Header -->
    <div class="page-header">
        <h1 class="page-title"><?= $this->title ?></h1>
        <div class="page-header-actions">
            <!--<form>
                <div class="input-search input-search-dark">
                    <i class="input-search-icon md-search" aria-hidden="true"></i>
                    <input type="text" class="form-control" name="" placeholder="Buscar...">
                </div>
            </form>-->
        </div>
    </div>
    <!-- Media Content -->
    <div id="mediaContent" class="page-content page-content-table" data-plugin="selectable">
        <!-- Actions -->
        <div class="page-content-actions">
            <div class="float-right">
                <div class="btn-group media-arrangement btn-group-flat" role="group">
                    <button class="btn btn-default active" id="arrangement-grid" type="button"><i class="icon md-view-module" aria-hidden="true"></i></button>
                    <button class="btn btn-default" id="arrangement-list" type="button"><i class="icon md-view-list" aria-hidden="true"></i></button>
                </div>
            </div>
            <div class="actions-inner">
                <!--<div class="checkbox-custom checkbox-primary checkbox-lg">
                    <input type="checkbox" id="media_all" class="selectable-all">
                    <label for="media_all"></label>
                </div>-->
            </div>
        </div>


        <!-- Media -->
        <?php Pjax::begin(['id' => 'pjax-imagenes-container', 'timeout' => 5000]); ?>

        <div class="media-list is-grid pb-50" data-plugin="animateList" data-animate="fade"
             data-child="li">
                 <?=
                 ListView::widget([
                     'dataProvider' => $dataProvider,
                     'id' => 'list-imagenes',
                     'layout' => '<div data-plugin="animateList" data-child=">li" class="items blocks blocks-100 blocks-xxl-4 blocks-xl-3 blocks-lg-3 blocks-md-2 blocks-sm-2">{items}</div>{pager}',
                     //'layout' => '{items}<div class="pager">{pager}</div>',
                     'itemOptions' => ['tag' => 'li', 'class' => ''],
                     'options' => [
                         'tag' => 'ul',
                     /* class' => 'blocks blocks-100 blocks-xxl-4 blocks-xl-3 blocks-lg-3 blocks-md-2 blocks-sm-2',
                       'data-plugin' => "animateList",
                       'data-child' => ">li", */
                     ],
                     'itemView' => '_thumbitem',
                     'pager' => [
                         'class' => InfiniteScrollPager::className(),
                         'widgetId' => 'list-imagenes',
                         'itemsCssClass' => 'items',
                         'nextPageLabel' => 'Cargar más imágenes',
                         'contentLoadedCallback' => 'function(data) { if(data.length < ' . $dataProvider->pagination->pageSize . ') $(".list-notas-actions").hide(); }',
                         'linkOptions' => [
                             'class' => 'btn btn-primary',
                         ],
                         'pluginOptions' => [
                             'loading' => [
                                 'msgText' => "<em>Cargando...</em>",
                                 'finishedMsg' => "<em>No se han encontrado mas resultados</em>",
                             ],
                             'behavior' => InfiniteScrollPager::BEHAVIOR_TWITTER,
                         ],
                     ],
                 ]);
                 ?>

        </div>
        <?php Pjax::end(); ?>
    </div>
</div>
</div>
<div class="site-action" data-plugin="actionBtn">

    <?= Html::a('<i class="front-icon md-upload animation-scale-up" aria-hidden="true"></i>
        <i class="back-icon md-close animation-scale-up" aria-hidden=ww"true"></i>', ['/imagenes/subir'], ['class' => 'btn-raised btn btn-success btn-floating remote-modal', 'target' => '_BLANK', 'data-target' => '#modal-subir', 'data-toggle' => 'modal']); ?>

    <div class="site-action-buttons">
        <button type="button" data-action="download" class="btn-raised btn btn-success btn-floating animation-slide-bottom">
            <i class="icon md-download" aria-hidden="true"></i>
        </button>
        <button type="button" data-action="trash" class="btn-raised btn btn-success btn-floating animation-slide-bottom ">
            <i class="icon md-delete" aria-hidden="true"></i>
        </button>
    </div>
    <input type="file" id="fileupload" name="upload" />
</div>


w

<div class="modal fade modal-scroll" id="modal-subir" tabindex="-1" role="dialog" aria-hidden="true">      
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>


<div class="modal fade modal-scroll" id="modal-recortes" tabindex="-1" role="dialog" aria-hidden="true">      
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        </div>
    </div>
</div>

backend/views/imagenes/input.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\ListView;
use nirvana\infinitescroll\InfiniteScrollPager;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\NoticiasSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

//\backend\assets\ImagenesAsset::register($this);

$this->title = 'Imágenes';

$this->params['breadcrumbs'][] = $this->title;
Yii::$app->params['page-header-show'] = false;
Yii::$app->params['page-content-show'] = false;
Yii::$app->params['page-body-class'] = 'app-media page-aside-left site-menubar-unfold';
?>

<!-- Media Content -->
<div class="page-main">
    <!-- Media Content Header -->
    <br>
    <!-- Media Content -->
    <div id="mediaContent" class="page-content page-content-table <?=  empty (Yii::$app->request->get('class')) ? '' : Yii::$app->request->get('class'); ?>" data-plugin="selectable">
        <!-- Actions -->
        <div class="page-content-actions">
            <h2 style="display:inline-block; margin-right: 2rem;">Selecciona una imagen</h2>
  
                <?= Html::a('<i class="front-icon md-upload animation-scale-up" aria-hidden="true"></i> Subir Nueva Imagen', ['/imagenes/subir'], ['class' => 'btn btn-success remote-modal', 'target' => '_BLANK', 'data-target' => '#modal-subir', 'data-toggle' => 'modal']); ?>



        </div>


        <!-- Media -->


        <div class="media-list is-grid pb-50" data-plugin="animateList" data-animate="fade" data-child="li">
            <?=
            ListView::widget([
                'dataProvider' => $dataProvider,
                'id' => 'galeria-input-list',
                'layout' => '<div class="items">{items}</div>{pager}',
                //'layout' => '{items}<div class="pager">{pager}</div>',
                'itemOptions' => ['tag' => 'li', 'class' => 'galeria-input-item'],
                'options' => [
                    'tag' => 'ul',
                    'class' => '',
                /* 'data-plugin' => "animateList",
                  'data-child' => ">li", */
                ],
                'itemView' => '_inputitem',
                'pager' => [
                    'class' => InfiniteScrollPager::className(),
                    'widgetId' => 'galeria-input-list',
                    'itemsCssClass' => 'items',
                    'nextPageLabel' => 'Cargar más Imágenes',
                    'contentLoadedCallback' => 'function(data) { if(data.length < ' . $dataProvider->pagination->pageSize . ') $(".list-notas-actions").hide(); }',
                    'linkOptions' => [
                        'class' => 'btn btn-primary btn-loadmore',
                    ],
                    'pluginOptions' => [
                        'loading' => [
                            'msgText' => "<em>Cargando...</em>",
                            'finishedMsg' => "<em>No se han encontrado mas resultados</em>",
                        ],
                        'behavior' => InfiniteScrollPager::BEHAVIOR_TWITTER,
                    ],
                ],
            ]);
            ?>

        </div>

    </div>
</div>

backend/views/imagenes/recortar.php
<?php
/* @var $this yii\web\View */

use backend\assets\CropperAsset;
use yii\helpers\Url;

CropperAsset::register($this);
?>

<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    <h4 class="modal-title"><strong>Recortar</strong> </h4>
</div>
<div class="modal-body">





    <div class="recortes-preview row">
        <?php
        $i = 1;
        foreach ($recortes as $recorte => $size):
            ?>

            <div class="col-md-3 recorte-item">
                <div class="recorte-header">
                    <h3><?= $recorte ?> </h3><button type="button" class="btn btn-primary btn-cropper" data-recorte="<?= $recorte ?>" data-image="img-recorte-<?= $recorte ?>" ><span class="fa fa-crop"></span> </button>
                </div>
                <img id="img-recorte-<?= $recorte ?>" class="img-fluid recorte recorte-<?= $recorte ?>" src="<?= $model->getUrl($recorte) ?>">


            </div>
            <?= $i % 4 == 0 ? '<div class="row"></div>' : '' ?>
            <?php
            $i++;
        endforeach;
        ?>

    </div>




    <div class="recortes-cropper">
        <div class="recortes-cropper-tools">
            <!-- <h3>Toolbar:</h3> -->
            <div class="btn-group">

                <button type="button" class="btn btn-success btn-cropper-tool" data-action="recortar" title="Crop">
                    <span class="fa fa-crop"></span> Recortar
                </button>
                <button type="button" class="btn btn-primary btn-cropper-tool" data-action="dragmode-move" title="Move">
                    <span class="fa fa-arrows"></span>
                </button>
            </div>

           <!-- <div class="btn-group">
                <button type="button" class="btn btn-primary btn-cropper-tool"  data-action="zoom-in" title="Zoom In">
                    <span class="fa fa-search-plus"></span>
                </button>
                <button type="button" class="btn btn-primary btn-cropper-tool"  data-action="zoom-out" title="Zoom Out">

                    <span class="fa fa-search-minus"></span>

                </button>
            </div>-->

            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-cropper-tool" data-action="move-left"  title="Move Left">
                    <span class="fa fa-arrow-left"></span>
                </button>
                <button type="button" class="btn btn-primary btn-cropper-tool" data-action="move-right"  title="Move Right">
                    <span class="fa fa-arrow-right"></span>
                </button>
                <button type="button" class="btn btn-primary btn-cropper-tool" data-action="move-up"  title="Move Up">
                    <span class="fa fa-arrow-up"></span>
                </button>
                <button type="button" class="btn btn-primary btn-cropper-tool" data-action="move-down"  title="Move Down">
                    <span class="fa fa-arrow-down"></span>
                </button>
            </div>

            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-cropper-tool" data-action="rotate-noclock"  title="Rotate Left">
                    <span class="fa fa-rotate-left"></span>
                </button>
                <button type="button" class="btn btn-primary btn-cropper-tool" data-action="rotate-clock"  title="Rotate Right">
                    <span class="fa fa-rotate-right"></span>
                </button>
            </div>

            <!--<div class="btn-group">
                <button type="button" class="btn btn-primary btn-cropper-tool" data-action="flip-hor"  title="Flip Horizontal">
                    <span class="fa fa-arrows-h"></span>
                </button>
                <button type="button" class="btn btn-primary btn-cropper-tool" data-action="flip-ver"  title="Flip Vertical">
                    <span class="fa fa-arrows-v"></span>
                </button>
            </div>-->

        </div>
        <img id="img-original" class="img-responsive" src="<?= $model->getUrl() ?>">
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn default" data-dismiss="modal">Cerrar</button>
</div>


<?php
$cropUrl = Url::toRoute(['/imagenes/recortar', 'id' => $id]);

$r_o = [];
foreach ($recortes as $recorte => $size) {

    $r_a = explode('x', $size);

    if (count($r_a) < 2)
        continue;
    $width = $r_a[0];
    $height = $r_a[1];
    
    $r_o[$recorte]['size'] = $size;
    $r_o[$recorte]['width'] = $width;
    $r_o[$recorte]['height'] = $height;
    if($height > 0)
        $r_o[$recorte]['aspectratio'] = $width / $height;
}


$recortes_options = json_encode($r_o);

$this->registerJs(<<<JAVASCRIPT
            
    var cropper = null;
    var recorte_selected = null;    
    var recortes_options = $recortes_options;
 
    initCropper('img-original',16/9,1280,720);
           

        
    $('.btn-cropper-tool').click(function(e){
        e.preventDefault();
        console.log("sapee");
        
        
        var action = $(this).data("action");
        
        switch(action){
            case "recortar": 
                actionRecortar();
            break;
            case "dragmode-move": 
                cropper.setDragMode("move");
            break;
            case "dragmode-crop": 
                cropper.setDragMode("crop");
            break;
            case "zoom-in": 
                cropper.zoom(0.1);
            break;
            case "zoom-out": 
                cropper.zoom(-0.1);
            break;
            case "move-up": 
                cropper.move(0,-10);
            break;
            case "move-down": 
                cropper.move(0,10);
            break;
            case "move-left": 
                cropper.move(-10,0);
            break;
            case "move-right": 
                cropper.move(10,0);
            break;
            case "rotate-noclock": 
                cropper.rotate(-45);
            break;
            case "rotate-clock": 
                cropper.rotate(45);
            break;
            case "flip-hor": 
                cropper.scaleX(-1);
            break;
            case "flip-ver": 
                cropper.scaleY(-1);
            break;
        }
    });    

        
        
    $('.btn-cropper').click(function(){
        
        console.log($(this).data("recorte"));
        recorte_selected = $(this).data("recorte");
        var r_o = recortes_options[recorte_selected];
        
        console.log(r_o);
        
        clearRecorteSelected();
        $(this).closest( ".recorte-item" ).addClass( "selected" );
        console.log( $(this));
        
        
        cropper.destroy();
        initCropper('img-original',r_o.aspectratio,r_o.width,r_o.height);
        
    });    

        
    function clearRecorteSelected(){
        $(".recorte-item" ).removeClass("selected");
    }
    function actionRecortar(){
        
        cropdata = cropper.getData();
        
        
        if(recorte_selected == null || recorte_selected == ""){
            return;
        }
        console.log("recortar");
        
        
        $.ajax({
          url: "$cropUrl",
          method: "POST",
          dataType :"json",
          data: {
                recorte: recorte_selected,
                cropdata: cropdata
            },
          context: document.body
        })
        .done(function(result) {
            reloadRecortes();
        });
    }
        
    function reloadRecortes(){
      
      $(".recorte").each(function( index ) {
        var urlimg = $( this ).attr("src");
        $( this ).attr("src", urlimg + "?" + new Date().getTime()); 
      });
        
    }
        
    function initCropper(imageid,aspectRatio,minWidth,minHeight){
        var image = document.getElementById(imageid);
        cropper = new Cropper(image, {
             aspectRatio: aspectRatio,
             viewMode: 1,
             checkCrossOrigin: false,
             cropBoxResizable : false,
             minCropBoxWidth: minWidth,
             minCropBoxHeight:minHeight,
            zoomable:false,
             
           crop: function(e) {
           /*  console.log(e.detail.x);
             console.log(e.detail.y);
             console.log(e.detail.width);
             console.log(e.detail.height);
             console.log(e.detail.rotate);
             console.log(e.detail.scaleX);
             console.log(e.detail.scaleY);*/
           }
     }); 
        
        

        
    }

    function destroyCropper(){
        cropper.destroy();
    } 
   
   
JAVASCRIPT
);

backend/views/imagenes/subir.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;
use kartik\form\ActiveForm;
use kartik\widgets\FileInput;
?>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title"><strong>Subir</strong> </h4>
</div>
<div class="modal-body">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>


    <?php
    echo '<label class="control-label">Imagen</label>';
    echo FileInput::widget([
        'name' => 'imagen-upload',
        'pluginOptions' => [
            //'initialPreview' => $fondo_initialpreview,
            // 'initialPreviewAsData' => true,
            'overwriteInitial' => true,
            'showPreview' => true,
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => true,
            'uploadUrl' => Url::to(['/imagenes/subir']),
            'minImageWidth' => 1280,
            'minImageHeight' => 720,
        ],
        'pluginEvents' => [
            "fileuploaded" => "function(e, data, previewId, index) { fileinput_uploaded_event(e, data, previewId, index);}",
        ],
    ]); ?>

    <?php ActiveForm::end(); ?>


</div>
<div class="modal-footer">
    <button type="button" class="btn default" data-dismiss="modal">Cerrar</button>
</div>


<?php
$this->registerJs(<<<JAVASCRIPT
            
        
        
    function fileinput_uploaded_event(e, data, previewId, index){

        //console.log(data);
        $("#modal-subir").trigger( "img-uploaded-event",data);
        $("#modal-subir").modal('toggle');
        toastr["success"]("La imagen ha sido cargada exitosamente!")
        $.pjax.reload({container: '#pjax-imagenes-container', timeout: 10000});
       
    }
   
   
JAVASCRIPT
);